#!/bin/bash -e
# $Id: make-deb 2770 2013-05-30 08:46:46Z dreibh $
#
# Debian Packaging Scripts
# Copyright (C) 2002-2017 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@iem.uni-due.de

./clean-deb
./make-deb trusty wily xenial yakkety zesty unstable
changeFiles=`ls *.changes`
for changeFile in $changeFiles ; do
   if [[ $changeFile =~ .*[0-9](ppa|ubuntu)[0-9].* ]] ; then
      dput ppa $changeFile
   else
      dput mentors $changeFile
   fi
done
