#!/bin/bash -e
#
# Travis CI Scripts
# Copyright (C) 2018-2019 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@iem.uni-due.de


. `dirname $0`/get-container


# ###### Linux ##############################################################
if [ "${TRAVIS_OS_NAME}" == "linux" ] ; then

   if [ "${DOCKER}" != "" ] ; then
      # NOTE: Using tmpfs for pbuilder and mock!
      # The build machine therefore needs a sufficient amount of RAM!
      sudo docker rm -f ${CONTAINER} || true
      sudo docker run -d \
         --name ${CONTAINER} \
         --tmpfs /var/cache/pbuilder:rw,exec,dev,size=4g \
         --tmpfs /var/lib/mock:rw,exec,dev,size=4g \
         --cap-add=SYS_ADMIN --cap-add=NET_ADMIN \
         --security-opt apparmor:unconfined \
         -v $(pwd):/travis -w /travis \
         $DOCKER tail -f /dev/null
      sudo docker ps
   fi


# ###### Other ##############################################################
elif [ "${TRAVIS_OS_NAME}" == "osx" ] ; then

   echo "Nothing to be done here."


# ###### Error ##############################################################
else
   echo >&2 "ERROR: Invalid setting of TRAVIS_OS_NAME=${TRAVIS_OS_NAME}"
   exit 1
fi
