#!/usr/bin/env bash
#
# Travis CI Scripts
# Copyright (C) 2018-2019 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@iem.uni-due.de

# Bash options:
set -e


if [ "${DOCKER}" != "" ] ; then
   # ====== Check configuration =============================================
   if [ "${VARIANT}" == "" ] ; then
      echo >&2 "ERROR: VARIANT is not set!"
      exit 1
   fi
   if [ "${TOOL}" == "" ] ; then
      echo >&2 "ERROR: TOOL is not set!"
      exit 1
   fi


   # ====== Get name of package =============================================
   CHANGELOG_HEADER="`head -n1 debian/changelog`"
   PACKAGE=`echo ${CHANGELOG_HEADER} | sed -e "s/(.*//" -e "s/ //g"`


   # ====== Set container name ==============================================
   CONTAINER=`echo "${PACKAGE}-${DOCKER}-${TOOL}" | sed -e "s/:/_/g"`
   if [ "${COMPILER_C}" != "" ] ; then
      CONTAINER="${CONTAINER}-${COMPILER_C}"
   fi
   export CONTAINER

   # echo "###### Using container ${CONTAINER} ######"

else
   export CONTAINER=""   # Not using docker -> no container!
fi
