# Created by: Thomas Dreibholz <dreibh@iem.uni-due.de>
# $FreeBSD$

PORTNAME=	libusrsctp
PORTVERSION=	1.0.0~rc1
CATEGORIES=	net
MASTER_SITES=	https://packages.nntb.no/software/libusrsctp/

MAINTAINER=	dreibh@iem.uni-due.de
COMMENT=	Portable SCTP Userland Stack

LICENSE=	BSD
# LICENSE_FILE=	${WRKSRC}/COPYING

USES=		cmake
USE_LDCONFIG=	yes

PLIST_SUB=      VERSION=${PORTVERSION}

.include <bsd.port.mk>
